import "@/styles/globals.css";

import localFont from "next/font/local";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const tearfundFont = localFont({
  src: [
    {
      path: "./font/FSMeWeb-Regular_rcfffc.woff2",
      weight: "400",
      style: "normal",
    },

    {
      path: "./font/FSMeWeb-Bold_ce2eoa.woff2",
      weight: "700",
      style: "bold",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${tearfundFont.className}`}>
      <body>{children}</body>
    </html>
  );
}
